import { notFound } from "next/navigation";
import { listMotels } from "@/lib/api/motels";
import { listRenters } from "@/lib/api/renters";
import { listBillingPeriods, listInvoices } from "@/lib/api/billing";
import { resolveMotelId, type MotelSearchParams } from "@/lib/motel-selection";
import InvoiceActions from "@/components/manager/invoice-actions";
import FinalizePeriod from "@/components/manager/finalize-period";
import Badge from "@/components/ui/badge";
import { formatVnd } from "@/lib/format/vnd";
import PageHeader from "@/components/ui/page-header";

const labels = { unpaid: "Chưa thanh toán", paid: "Đã gửi", overdue: "Quá hạn" } as const;
export default async function InvoicesPage({ params, searchParams }: { params: Promise<{ periodId: string }>; searchParams: Promise<MotelSearchParams> }) {
  const [route, query, motels] = await Promise.all([params, searchParams, listMotels()]); const motelId = resolveMotelId(motels, query); if (!motelId) return <p>Chưa có nhà trọ.</p>; const motel = motels.find((item) => item.id === motelId);
  const [periods, renters, invoices] = await Promise.all([listBillingPeriods(motelId), listRenters(motelId), listInvoices(motelId, route.periodId)]); const period = periods.find((item) => item.id === route.periodId); if (!period) notFound(); const renterNames = new Map(renters.map((renter) => [renter.id, renter.name]));
  return <section className="space-y-6"><div><PageHeader title={`Hóa đơn tháng ${String(period.month).padStart(2, "0")}/${period.year}`} description="Kiểm tra từng khoản trước khi chốt kỳ." /></div><div className="rounded-card border border-border bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-text-muted">Tổng số hóa đơn</p><p className="font-heading text-2xl font-bold tabular-nums text-text">{invoices.length}</p></div><FinalizePeriod motelId={motelId} periodId={period.id} disabled={period.status !== "draft" || invoices.length === 0} /></div></div>{invoices.length === 0 ? <p className="rounded-card border border-dashed border-border bg-surface p-6 text-text-muted">Chưa có hóa đơn. Tạo hóa đơn sau khi hoàn tất chỉ số và kiểm tra phòng đủ điều kiện.</p> : <div className="grid gap-4">{invoices.map((invoice) => <article key={invoice.id} className="rounded-card border border-border bg-surface p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold text-text-muted">PHÒNG</p><h2 className="font-heading text-lg font-semibold text-text">{invoice.roomName}</h2><p className="mt-1 text-sm text-text-muted">Khách: {renterNames.get(invoice.renterId) ?? "Không rõ"}</p></div><Badge tone={invoice.paymentStatus === "paid" ? "success" : invoice.paymentStatus === "overdue" ? "danger" : "warning"} label={labels[invoice.paymentStatus]} /></div><dl className="mt-4 grid gap-2 border-t border-border pt-4 text-sm sm:grid-cols-2"><div className="flex justify-between gap-3"><dt className="text-text-muted">Tiền thuê</dt><dd className="font-medium tabular-nums text-text">{formatVnd(invoice.rentAmount)}</dd></div><div className="flex justify-between gap-3"><dt className="text-text-muted">Điện</dt><dd className="font-medium tabular-nums text-text">{formatVnd(invoice.electricityCost)}</dd></div><div className="flex justify-between gap-3"><dt className="text-text-muted">Nước</dt><dd className="font-medium tabular-nums text-text">{formatVnd(invoice.waterCost)}</dd></div><div className="flex justify-between gap-3"><dt className="text-text-muted">Phí khác</dt><dd className="max-w-[65%] text-right text-text">{invoice.otherFees.length ? invoice.otherFees.map((fee) => `${fee.name}: ${formatVnd(fee.amount)}`).join(", ") : "Không có"}</dd></div></dl><div className="mt-4 flex flex-wrap items-end justify-between gap-4 border-t border-border pt-4"><div><p className="text-sm text-text-muted">Tổng cộng</p><p className="font-heading text-xl font-bold tabular-nums text-text">{formatVnd(invoice.totalAmount)}</p></div><InvoiceActions motelId={motelId} invoice={invoice} bankAccount={motel?.bankAccount ?? null} /></div>{invoice.paidAt && <p className="mt-3 text-xs text-text-muted">Đã thanh toán: {new Date(invoice.paidAt).toLocaleString("vi-VN")}</p>}</article>)}</div>}</section>;
}
