"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { saveCaptureReadings, uploadMeterPhoto, isReadingConflict } from "@/lib/api/capture.client";
import { CaptureQueue, CaptureQueueUnavailableError } from "@/lib/capture/queue";
import { syncCaptureQueue } from "@/lib/capture/sync";
import { calculateMeterPreview } from "@/lib/billing-calculation";
import type { BillingPeriodDetailResponse, MeterReadingResponse } from "@/lib/api/types";

export default function CaptureReadingClient({ motelId, period, reading }: { motelId: string; period: BillingPeriodDetailResponse; reading: MeterReadingResponse }) {
  const router = useRouter(); const [value, setValue] = useState(reading.currentReading ?? ""); const [photo, setPhoto] = useState<File>(); const [message, setMessage] = useState(""); const [syncState, setSyncState] = useState("Chưa đồng bộ"); const locked = period.status !== "draft"; const preview = calculateMeterPreview(reading.previousReading, value, reading.type === "electric" ? "3500" : "15000");
  const sync = useCallback(async () => { if (locked) return; try { const queue = new CaptureQueue("browser"); const result = await syncCaptureQueue(queue, async (item) => { await saveCaptureReadings(item.motelId, item.periodId, { readings: item.readings }); }, async (item) => { await uploadMeterPhoto(item.motelId, item.periodId, item.readingId, new File([item.file], "meter-photo", { type: item.file.type })); }); setSyncState(result.readings.conflicts ? "Cần kiểm tra xung đột" : result.readings.failed || result.photos.failed ? "Đang chờ kết nối" : result.readings.sent || result.photos.sent ? "Đã đồng bộ" : "Đã lưu trên thiết bị"); } catch { setSyncState("Thiết bị không hỗ trợ lưu ngoại tuyến"); setMessage("Không thể đồng bộ lúc này"); } }, [locked]);
  useEffect(() => { const onReconnect = () => void sync(); window.addEventListener("online", onReconnect); const timer = window.setTimeout(() => void sync(), 0); return () => { window.clearTimeout(timer); window.removeEventListener("online", onReconnect); }; }, [sync]);
  async function save() { if (locked) return; try { const queue = new CaptureQueue("browser"); await queue.enqueue({ managerId: "browser", motelId, periodId: period.id, periodStatus: "draft", readings: [{ roomId: reading.roomId, type: reading.type, currentReading: value, expectedUpdatedAt: reading.updatedAt }] }); if (photo) await queue.enqueuePhoto({ managerId: "browser", motelId, periodId: period.id, readingId: reading.id, periodStatus: "draft", file: photo }); await sync(); setMessage("Đã lưu. Sẽ đồng bộ khi có mạng."); } catch (error) { setMessage(error instanceof CaptureQueueUnavailableError ? "Thiết bị không hỗ trợ lưu ngoại tuyến." : isReadingConflict(error) ? "Chỉ số đã thay đổi trên máy chủ. Nhập lại trước khi lưu." : "Không thể lưu chỉ số"); } }
  return <section className="mx-auto max-w-lg space-y-5"><button className="text-sm text-primary" onClick={() => router.back()}>← Quay lại</button><h1 className="font-heading text-2xl font-bold">{reading.type === "electric" ? "Điện" : "Nước"}</h1><p className="text-text-muted">Chỉ số trước: {reading.previousReading}</p>{locked && <p role="status" className="rounded-card border border-warning bg-warning-bg p-3 text-warning">Kỳ đã chốt. Chỉ xem.</p>}<label className="block space-y-2">Chỉ số hiện tại<input disabled={locked} autoFocus inputMode="decimal" value={value} onChange={(event) => setValue(event.target.value)} className="min-h-14 w-full rounded-input border border-border px-4 text-2xl" /></label><label className="block space-y-2">Ảnh công tơ<input disabled={locked} type="file" accept="image/jpeg,image/png" capture="environment" onChange={(event) => setPhoto(event.target.files?.[0])} /></label>{preview && <p className="rounded-card border border-border bg-surface p-3">Dùng {preview.usage} · Ước tính {preview.cost} ₫</p>}<p role="status" className="text-sm text-text-muted">{syncState}</p>{photo && <div className="space-y-2"><img src={URL.createObjectURL(photo)} alt="Ảnh công tơ đã chọn" loading="lazy" className="h-32 w-full rounded-card object-cover" /><button type="button" onClick={() => setPhoto(undefined)} className="text-sm text-primary">Chụp lại ảnh</button></div>}<button disabled={locked} onClick={save} className="min-h-12 w-full rounded-input bg-primary px-4 font-semibold text-surface disabled:opacity-50">Lưu và đồng bộ sau</button>{message && <p role="status" className="rounded-card border border-border p-3">{message}</p>}</section>;
}
