"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { saveCaptureReadings, uploadMeterPhoto, isReadingConflict } from "@/lib/api/capture.client";
import { CaptureQueue, CaptureQueueUnavailableError } from "@/lib/capture/queue";
import { syncCaptureQueue } from "@/lib/capture/sync";
import { calculateMeterPreview } from "@/lib/billing-calculation";
import type { BillingPeriodDetailResponse, MeterReadingResponse } from "@/lib/api/types";

export default function CaptureReadingClient({ motelId, period, reading, roomName, roomReadings }: { motelId: string; period: BillingPeriodDetailResponse; reading: MeterReadingResponse; roomName: string; roomReadings: MeterReadingResponse[] }) {
  const router = useRouter(); const [currentId, setCurrentId] = useState(reading.id); const active = roomReadings.find((item) => item.id === currentId) ?? reading; const index = roomReadings.findIndex((item) => item.id === currentId); const [value, setValue] = useState(active.currentReading ?? ""); const [photo, setPhoto] = useState<File>(); const [message, setMessage] = useState(""); const [syncState, setSyncState] = useState("Chưa đồng bộ"); const locked = period.status !== "draft"; const preview = calculateMeterPreview(active.previousReading, value, active.type === "electric" ? "3500" : "15000");
  const sync = useCallback(async () => { if (locked) return; try { const queue = new CaptureQueue("browser"); const result = await syncCaptureQueue(queue, async (item) => { await saveCaptureReadings(item.motelId, item.periodId, { readings: item.readings }); }, async (item) => { await uploadMeterPhoto(item.motelId, item.periodId, item.readingId, new File([item.file], "meter-photo", { type: item.file.type })); }); setSyncState(result.readings.conflicts ? "Cần kiểm tra xung đột" : result.readings.failed || result.photos.failed ? "Đang chờ kết nối" : result.readings.sent || result.photos.sent ? "Đã đồng bộ" : "Đã lưu trên thiết bị"); } catch { setSyncState("Ngoại tuyến · hàng đợi giữ trên thiết bị"); } }, [locked]);
  useEffect(() => { const onReconnect = () => void sync(); window.addEventListener("online", onReconnect); const timer = window.setTimeout(() => void sync(), 0); return () => { window.clearTimeout(timer); window.removeEventListener("online", onReconnect); }; }, [sync]);
  const move = (next: MeterReadingResponse) => { setCurrentId(next.id); setValue(next.currentReading ?? ""); setPhoto(undefined); setMessage(""); };
  const next = roomReadings[index + 1];
  async function save(nextReading?: MeterReadingResponse) { if (locked) return; try { const queue = new CaptureQueue("browser"); await queue.enqueue({ managerId: "browser", motelId, periodId: period.id, periodStatus: "draft", readings: [{ roomId: active.roomId, type: active.type, currentReading: value, expectedUpdatedAt: active.updatedAt }] }); if (photo) await queue.enqueuePhoto({ managerId: "browser", motelId, periodId: period.id, readingId: active.id, periodStatus: "draft", file: photo }); await sync(); setMessage("Đã lưu chỉ số"); if (nextReading) move(nextReading); } catch (error) { setMessage(error instanceof CaptureQueueUnavailableError ? "Thiết bị không hỗ trợ lưu ngoại tuyến." : isReadingConflict(error) ? "Xung đột: chỉ số máy chủ đã đổi. Nhập lại." : "Không thể lưu chỉ số"); } }
  const title = useMemo(() => `${roomName} · ${active.type === "electric" ? "Điện" : "Nước"}`, [roomName, active.type]);
  return <section className="mx-auto max-w-lg space-y-5"><button className="text-sm text-primary" onClick={() => router.push(`/capture/${period.id}?motel=${encodeURIComponent(motelId)}`)}>← Danh sách phòng</button><div className="flex items-center justify-between"><h1 className="font-heading text-2xl font-bold">{title}</h1><span className="text-sm text-text-muted">{index + 1}/{roomReadings.length}</span></div><p className="text-text-muted">Chỉ số trước: {active.previousReading}</p>{locked && <p role="status" className="rounded-card border border-warning bg-warning-bg p-3 text-warning">Kỳ đã chốt · Chỉ xem</p>}<label className="block space-y-2">Chỉ số hiện tại<input disabled={locked} autoFocus inputMode="decimal" value={value} onChange={(event) => setValue(event.target.value)} className="min-h-14 w-full rounded-input border border-border px-4 text-2xl" /></label>{preview && <p className="rounded-card border border-border bg-surface p-3">Dùng {preview.usage} · Ước tính {preview.cost} ₫</p>}<label className="block space-y-2">Ảnh công tơ<input disabled={locked} type="file" accept="image/jpeg,image/png" capture="environment" onChange={(event) => setPhoto(event.target.files?.[0])} /></label>{photo && <div className="space-y-2"><img src={URL.createObjectURL(photo)} alt="Ảnh công tơ đã chọn" className="h-32 w-full rounded-card object-cover" /><button type="button" onClick={() => setPhoto(undefined)} className="text-sm text-primary">Chụp lại ảnh</button></div>}<p role="status" className="text-sm text-text-muted">{syncState}</p><div className="flex gap-2"><button disabled={locked} onClick={() => void save(next)} className="min-h-12 flex-1 rounded-input bg-primary px-4 font-semibold text-surface disabled:opacity-50">{next ? "Lưu và tiếp" : "Lưu"}</button>{!next && <button disabled={locked} onClick={() => void save()} className="min-h-12 rounded-input border border-border px-4">Lưu</button>}</div>{message && <p role="status" className="rounded-card border border-border p-3">{message}</p>}</section>;
}
