import { serverGetRenter } from "@/lib/api/renter.server";
import type { RenterInvoiceDetail } from "@/lib/api/types";
import { formatVnd } from "@/lib/format/vnd";
import { formatDate } from "@/lib/format/date";
import Image from "next/image";
import Link from "next/link";
import InvoiceQr from "@/components/renter/invoice-qr";
import PaymentProofPanel from "@/components/renter/payment-proof-panel";

export default async function RenterInvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const invoice = await serverGetRenter<RenterInvoiceDetail>(`/api/renter/invoices/${encodeURIComponent(id)}`);
  return <section className="space-y-6"><Link href="/portal/bills" className="text-sm font-semibold text-primary underline">← Lịch sử hóa đơn</Link><div><h1 className="font-heading text-2xl font-bold text-text">Hóa đơn tháng {String(invoice.month).padStart(2, "0")}/{invoice.year}</h1><p className="mt-1 text-sm text-text-muted">Tạo ngày {formatDate(invoice.createdAt)}</p></div><article className="space-y-4 rounded-card border border-border p-5"><h2 className="font-heading text-lg font-semibold text-text">Phòng {invoice.roomName}</h2><dl className="space-y-3"><div className="flex justify-between gap-4"><dt>Tiền thuê</dt><dd>{formatVnd(invoice.rentAmount)}</dd></div><div className="flex justify-between gap-4"><dt>Điện ({invoice.electricityUsage} kWh)</dt><dd>{formatVnd(invoice.electricityCost)}</dd></div><div className="flex justify-between gap-4"><dt>Nước ({invoice.waterUsage} m³)</dt><dd>{formatVnd(invoice.waterCost)}</dd></div>{invoice.otherFees.map((fee) => <div className="flex justify-between gap-4" key={fee.name}><dt>{fee.name}</dt><dd>{formatVnd(fee.amount)}</dd></div>)}<div className="flex justify-between gap-4 border-t border-border pt-3 font-bold text-text"><dt>Tổng cộng</dt><dd>{formatVnd(invoice.totalAmount)}</dd></div></dl><div className="rounded-input bg-canvas p-3"><p className="font-semibold text-text">Nội dung chuyển khoản</p><p className="mt-1 text-sm">{invoice.transferDescription ?? "Thanh toán hóa đơn nhà trọ"}</p>{invoice.bankAccount ? <p className="mt-2 text-sm text-text-muted">{invoice.bankAccount.accountName} · {invoice.bankAccount.accountNumber}</p> : <p className="mt-2 text-sm text-warning">Chưa cập nhật thông tin ngân hàng — vui lòng liên hệ chủ nhà trọ</p>}</div>{invoice.qrCodeData && <InvoiceQr payload={invoice.qrCodeData} />}</article><PaymentProofPanel invoiceId={invoice.id} paymentStatus={invoice.paymentStatus} paymentMethod={invoice.paymentMethod} />{invoice.meterPhotos?.length ? <section><h2 className="font-heading text-lg font-semibold text-text">Ảnh chỉ số</h2><div className="mt-3 grid grid-cols-2 gap-3">{invoice.meterPhotos.map((photo) => <figure key={photo.type}><Image src={photo.signedUrl} alt={photo.type === "electric" ? "Ảnh chỉ số điện" : "Ảnh chỉ số nước"} width={640} height={640} unoptimized className="aspect-square w-full rounded-input object-cover" /><figcaption className="mt-1 text-sm text-text-muted">{photo.type === "electric" ? "Điện" : "Nước"}{photo.capturedAt ? ` · ${formatDate(photo.capturedAt)}` : ""}</figcaption></figure>)}</div></section> : null}</section>;
}
