import { serverGetRenter } from "@/lib/api/renter.server";
import type { RenterContract } from "@/lib/api/types";
import { formatVnd } from "@/lib/format/vnd";
import ContractActions from "@/components/renter/contract-actions";

export default async function RenterContractPage() {
  const contract = await serverGetRenter<RenterContract>("/api/renter/contract");
  const status = contract.status === "active" ? "Đang hiệu lực" : contract.status === "draft" ? "Chờ ký" : contract.status === "expired" ? "Đã hết hạn" : "Đã chấm dứt";
  return <section className="space-y-6"><div className="rounded-card bg-primary p-5 text-surface"><p className="text-xs font-semibold text-primary-fixed">HỢP ĐỒNG THUÊ</p><h1 className="mt-2 font-heading text-2xl font-bold">Xem và ký hợp đồng</h1><p className="mt-2 text-primary-fixed">Đọc kỹ điều khoản trước khi xác nhận bằng mã OTP.</p></div><article className="space-y-5 rounded-card border border-border bg-surface p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-heading text-lg font-semibold text-text">Tóm tắt hợp đồng</h2><span className="rounded-full bg-warning-bg px-3 py-1 text-sm font-semibold text-warning">{status}</span></div><dl className="grid gap-4 border-y border-border py-4 sm:grid-cols-3"><div><dt className="text-sm text-text-muted">Tiền thuê / tháng</dt><dd className="mt-1 font-semibold tabular-nums text-text">{formatVnd(contract.monthlyRent)}</dd></div><div><dt className="text-sm text-text-muted">Tiền cọc</dt><dd className="mt-1 font-semibold tabular-nums text-text">{formatVnd(contract.deposit)}</dd></div><div><dt className="text-sm text-text-muted">Thời hạn</dt><dd className="mt-1 text-text">{contract.startDate} – {contract.endDate}</dd></div></dl><div className="space-y-4"><h2 className="font-heading text-lg font-semibold text-text">Điều khoản</h2>{contract.clauses.map((clause, index) => <section key={`${clause.title}-${index}`} className="rounded-input bg-canvas p-4"><h3 className="font-semibold text-text">{clause.title}</h3><p className="mt-2 whitespace-pre-wrap text-base leading-7 text-text-body">{clause.content}</p></section>)}</div><ContractActions contract={contract} /></article></section>;
}
